### ISSUE TITLE
能否增加对树莓派的支持呀？

### ISSUE THREAD

**Issue by czweb** [neroxps/hassio-addons#1]
bluetooth_scan_tracker的作者大人我也想用用看，能加让树莓派也支持，最近在研究蓝牙近场检测，用于开锁或是其它自动功能。。。。。

**Comment by neroxps** [comment]
L大论坛里面发了个蓝牙信号换算米数的插件你试试？

我这addons 不安全。而且没法近场

**Comment by czweb** [comment]
放心，我不用近场，只用用你这个做检测，不涉及安全
